Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('1', 'Activos', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('2', 'Pasivos', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('3', 'Patrimonio', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('4', 'Ingresos', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('5', 'Costos', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('6', 'Gastos', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('7', 'Otros ingresos', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('8', 'Otros gastos', '', 1, 0, 0);
Insert into `TipoMoneda` (nombre) values ('Local');
Insert into `TipoMoneda` (nombre) values ('Sistema');
Insert into `TipoMoneda` (nombre) values ('Extranjera');
Insert into `Estado` (nombre) values ('Abierto');
Insert into `Estado` (nombre) values ('Cerrado');
Insert into `Estado` (nombre) values ('Abierto excepto ventas');
Insert into `TipoAsiento` (nombre) values ('AS');
-- Inserts del profe --
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('1-1', 'Activos Circulantes', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('1-1-01', 'Efectivo y Bancos', '', 1, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('1-1-01-01', 'Caja Chica', '', 0, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('1-1-01-02', 'Banco Nacional Dolares', '', 0, 0, 0);
Insert into `Cuenta` (codigo, nombre, nombreExtranjero, titulo, saldoSistema, saldoLocal) values ('1-1-01-03', 'Banco Nacional Colones', '', 0, 0, 0);
