INSERT INTO `Pais` (nombre) VALUES ( 'Austria');
INSERT INTO `Pais` (nombre) VALUES ( 'Argentina');
INSERT INTO `Pais` (nombre) VALUES ( 'Australia');
INSERT INTO `Pais` (nombre) VALUES ( 'Bolivia');
INSERT INTO `Pais` (nombre) VALUES ( 'Brazil');
INSERT INTO `Pais` (nombre) VALUES ( 'Chile');
INSERT INTO `Pais` (nombre) VALUES ( 'China');
INSERT INTO `Pais` (nombre) VALUES ( 'Canada');
INSERT INTO `Pais` (nombre) VALUES ( 'Colombia');
INSERT INTO `Pais` (nombre) VALUES ( 'Costa Rica');
INSERT INTO `Pais` (nombre) VALUES ( 'Cuba');
INSERT INTO `Pais` (nombre) VALUES ( 'Ecuador');
INSERT INTO `Pais` (nombre) VALUES ( 'El Salvador');
INSERT INTO `Pais` (nombre) VALUES ( 'France');
INSERT INTO `Pais` (nombre) VALUES ( 'Guatemala');
INSERT INTO `Pais` (nombre) VALUES ( 'Haiti');
INSERT INTO `Pais` (nombre) VALUES ( 'Honduras');
INSERT INTO `Pais` (nombre) VALUES ( 'India');
INSERT INTO `Pais` (nombre) VALUES ( 'Italy');
INSERT INTO `Pais` (nombre) VALUES ( 'Jamaica');
INSERT INTO `Pais` (nombre) VALUES ( 'Japan');
INSERT INTO `Pais` (nombre) VALUES ( 'Mexico');
INSERT INTO `Pais` (nombre) VALUES ( 'Panama');
INSERT INTO `Pais` (nombre) VALUES ( 'Paraguay');
INSERT INTO `Pais` (nombre) VALUES ( 'Peru');
INSERT INTO `Pais` (nombre) VALUES ( 'Puerto Rico');
INSERT INTO `Pais` (nombre) VALUES ( 'Russian Federation');
INSERT INTO `Pais` (nombre) VALUES ( 'Switzerland');
INSERT INTO `Pais` (nombre) VALUES ( 'United Kingdom');
INSERT INTO `Pais` (nombre) VALUES ( 'United States');
INSERT INTO `Pais` (nombre) VALUES ( 'Uruguay');
INSERT INTO `Pais` (nombre) VALUES ( 'Vanuatu');
INSERT INTO `Pais` (nombre) VALUES ( 'Venezuela');
