create procedure crearEstado (Nombre varchar(45)) begin INSERT INTO Estado (nombre) values(Nombre); end;
create procedure crearPeriodoContable (IdEstado int, Ano int, Mes int, InicioC date, FinC date, InicioD date, FinD date, InicioV date, FinV date) begin INSERT INTO PeriodoContable (idEstado, anio, mes, inicioContable, finContable, inicioDocumento, finDocumento, inicioVencimiento, finVencimiento) values(IdEstado, Ano, Mes, InicioC, FinC, InicioD, FinD, InicioV, FinV); end;
create procedure crearTipoAsiento (Nombre varchar(2)) begin INSERT INTO TipoAsiento (nombre) values(Nombre); end;
create procedure crearAsiento (FechaContabilizacion date, FechaDocumento date, Referencia1 varchar(20), Referencia2 varchar(20), IdTipoAsiento int) begin INSERT INTO Asiento (fechaContabilizacion, fechaDocumento, Referencia1, Referencia2, idTipoAsiento) values(FechaContabilizacion, FechaDocumento, Referencia1, Referencia2, IdTipoAsiento); end;
create procedure crearCuenta (Codigo varchar(45), Nombre varchar(45), NombreExtranjero varchar(45), Titulo boolean, Saldo decimal(10,4)) begin INSERT INTO Cuenta (Codigo, Nombre, NombreExtranjero, Titulo, Saldo) values(Codigo, Nombre, NombreExtranjero, Titulo, Saldo); end;
create procedure crearAsientoxCuenta (Debe bit, Sistema decimal(10,4), Local decimal(10,4), Extranjero decimal(10,4), Asiento int, Cuenta int) begin INSERT INTO AsientoxCuenta (debe, montoSistema, montoLocal, montoExtranjero, idAsiento, idCuenta)  values(Debe, Sistema, Local, Extranjero, Asiento, Cuenta); end;
create procedure crearTipoCambio (RelacionCompra decimal(10,4), RelacionVenta decimal(10,4), Fecha date, nombMoneda varchar(45)) begin declare idMoneda INT; SELECT Moneda.idMoneda from Moneda where nombre = nombMoneda into idMoneda; INSERT INTO TipoCambio (relacionCompra,relacionVenta, Fecha, idMoneda) values(RelacionCompra, RelacionVenta, Fecha, idMoneda); end;
create procedure crearTipoMoneda (Nombre varchar(10)) begin INSERT INTO TipoMoneda (Nombre) values(Nombre); end;
create procedure crearMoneda (Nombre varchar(10), BCCR boolean, TipoMoneda varchar(45)) begin DECLARE IdTipoMoneda INT; SELECT idTipoMoneda from TipoMoneda where nombre = TipoMoneda into IdTipoMoneda; INSERT INTO Moneda (Nombre, BCCR, IdTipoMoneda) values(Nombre, BCCR, IdTipoMoneda); end;
